In [1]:
import numpy as np

In [2]:
X = np.array([[1,2,3], [4,5,6],[7,8,9],[10,11,12]])

In [3]:
V = np.array([1,0,1])

In [4]:
y = np.empty_like(X)

In [5]:
y

array([[3458764513820540928, 6917537793605431266,                   6],
       [                  0,          4294967296, 3471831545649718635],
       [3258693196413547109, 4120851027731165282, 3831779556157697337],
       [3617293630180964452, 8386112019186082148,    1688849860293493]])

In [6]:
X

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
for i in range(4):
    y[i,:] = X[i,:] + V

In [8]:
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [9]:
z = np.empty_like(X)

In [12]:
z.shape

(4, 3)

In [13]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])


In [14]:
vv = np.tile(v, (4, 1)) 


In [15]:
vv

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [16]:
y = x + vv 


In [17]:
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [29]:
class ChangeValue:
    def __init__(self, func):
        self.func = func

    def __call__(self, *args, **kwargs):
        for item in args:
            print(self.func(item))
            #item.value = self._fun(item.value)
        return args

ChangeValue(lambda value: value.replace(' ', ''))('he he')

hehe


('he he',)

In [19]:
lambda value: value.replace('', '')

<function __main__.<lambda>(value)>

In [24]:
class Hehe:

        def __init__(self, func):
            self.func = func

        def __call__(self, *args, **kwargs):
            for item in args:
                print(self.func(item))

Hehe(lambda v: v.replace(' ', ''))('he he')

hehe
