In [1]:
import numpy as np

In [2]:
X = np.arange(25).reshape(5,5)

In [3]:
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [4]:
print(X[X>10]) #布尔表达式的使用

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [5]:
print(X[X<7])

[0 1 2 3 4 5 6]


In [6]:
print(X[(X>10)& (X<18)])

[11 12 13 14 15 16 17]


In [7]:
X[(X>10)& (X<18)] = -1
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 -1 18 19]
 [20 21 22 23 24]]


In [17]:
#集合运算

x = np.array([1,2,3,4,5])
y = np.array([6,7,2,8,4])

print(np.intersect1d(x,y)) #The elements that are both in x and y
print(np.setdiff1d(x,y)) #The elements that are in x that are not in y
print(np.union1d(x,y)) #All the elements of x and y


[2 4]
[1 3 5]
[1 2 3 4 5 6 7 8]


In [10]:
x = np.random.randint(1,11,size=(10,))
print(x)

[ 9 10 10  4  2  5  9  1  6  6]


In [11]:
print(np.sort(x)) 
""" 函数在其他地方给x排序 不会改变原数组"""

[ 1  2  4  5  6  6  9  9 10 10]


In [12]:
print(x)

[ 9 10 10  4  2  5  9  1  6  6]


In [13]:
print(np.sort(np.unique(x)))

[ 1  2  4  5  6  9 10]


In [14]:
x.sort()
print(x)
"""原数组x也排序好了 (改变了原数组)"""

[ 1  2  4  5  6  6  9  9 10 10]


In [15]:
X = np.random.randint(1,11,size= (5,5))
print(X)

[[ 7  2  3  6  3]
 [ 3  4  5  2  5]
 [ 8  7  5  6  3]
 [ 1  3  7  7  6]
 [ 2  2  9 10  8]]


In [18]:
"""当 np.sort() 当做函数使用时，它不会对ndarray进行就地排序，
即不更改被排序的原始 ndarray。
但是，如果将 sort 当做方法，
ndarray.sort() 会就地排序 ndarray，即原始数组会变成排序后的数组。
"""


X = np.arange(1,26).reshape(5,5)
print(X)
Y = X[X%2 != 1]
print(Y)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [19]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

print(x)
print(y)


[1 2 3 4]
[5 6 7 8]


In [20]:
print(x+y)

[ 6  8 10 12]


In [21]:
print(np.add(x,y))

[ 6  8 10 12]


In [22]:
x = np.array([1,2,3,4]).reshape(2,2)
print(x)

[[1 2]
 [3 4]]


In [23]:
y = np.array([5,6,7,8]).reshape(2,2)
print(y)

[[5 6]
 [7 8]]


In [24]:
print(x/y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [25]:
print(x)

[[1 2]
 [3 4]]


In [26]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [29]:
print(np.power(x,2))

[[ 1  4]
 [ 9 16]]


In [30]:
print(x)

[[1 2]
 [3 4]]


In [31]:
print(x.mean())

2.5


In [33]:
#对其执行运算的 ndarray 必须具有相同的形状或者可以广播
X = np.array([1,2,3,4]).reshape(2,2)
print(X)

[[1 2]
 [3 4]]


In [34]:
Y = np.array([5.5,6.5,7.5,8.5]).reshape(2,2)
print(Y)

[[5.5 6.5]
 [7.5 8.5]]


In [35]:
print('X + Y = \n', X + Y)

X + Y = 
 [[ 6.5  8.5]
 [10.5 12.5]]


In [36]:
print('add(X,Y) = \n', np.add(X,Y))

add(X,Y) = 
 [[ 6.5  8.5]
 [10.5 12.5]]


In [37]:
print('subtract(X,Y) = \n', np.subtract(X,Y))

subtract(X,Y) = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]


In [38]:
print('multiply(X,Y) = \n', np.multiply(X,Y))

multiply(X,Y) = 
 [[ 5.5 13. ]
 [22.5 34. ]]


In [39]:
print('divide(X,Y) = \n', np.divide(X,Y))

divide(X,Y) = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]


In [40]:
x = np.array([1,2,3,4])


In [41]:
print('EXP(x) =', np.exp(x))

EXP(x) = [ 2.71828183  7.3890561  20.08553692 54.59815003]


In [42]:
print('SQRT(x) =',np.sqrt(x))

SQRT(x) = [1.         1.41421356 1.73205081 2.        ]


In [43]:
print('POW(x,2) =',np.power(x,2)) 

POW(x,2) = [ 1  4  9 16]


In [44]:

# Create a 1000 x 20 ndarray with random integers in the half-open interval [0, 5001).
X = np.random.randint(0,50001, size = (1000, 20))

# print the shape of X
print(X)



[[ 2527 29691 33400 ...  8581 21662 19040]
 [48354 43903  4344 ... 44853 17101 14288]
 [14010 37560 23682 ... 14546 40496  7783]
 ...
 [  400 19326 39641 ...  8201 33323 27326]
 [ 1015 36081 42014 ... 36816 12835  9809]
 [25024 33814  4525 ... 23188  9842 49697]]


In [45]:
print(len(X))

1000


In [47]:
ave_cols = np.mean(X)
print(ave_cols)

25125.49295


In [49]:
std_cols = np.std(X)
print(std_cols)

14449.96433390236
