In [4]:
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

import numpy as np
import torch

import helper

In [5]:
x = torch.rand(3, 2)
x

tensor([[0.6878, 0.9872],
        [0.5892, 0.5237],
        [0.6386, 0.1619]])

In [6]:
y = torch.ones(x.size())
y

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [7]:
z = x + y
z

tensor([[1.6878, 1.9872],
        [1.5892, 1.5237],
        [1.6386, 1.1619]])

In [8]:
# Return a new tensor z + 1
z.add(1)

tensor([[2.6878, 2.9872],
        [2.5892, 2.5237],
        [2.6386, 2.1619]])

In [9]:
# z tensor is unchanged
z

tensor([[1.6878, 1.9872],
        [1.5892, 1.5237],
        [1.6386, 1.1619]])

In [10]:
# Add 1 and update z tensor in-place
z.add_(1)

tensor([[2.6878, 2.9872],
        [2.5892, 2.5237],
        [2.6386, 2.1619]])

In [11]:
z

tensor([[2.6878, 2.9872],
        [2.5892, 2.5237],
        [2.6386, 2.1619]])

In [12]:
z.size()

torch.Size([3, 2])

In [13]:
z.resize_(2, 3)

tensor([[2.6878, 2.9872, 2.5892],
        [2.5237, 2.6386, 2.1619]])

In [14]:
z

tensor([[2.6878, 2.9872, 2.5892],
        [2.5237, 2.6386, 2.1619]])

In [15]:
z.size()

torch.Size([2, 3])

In [16]:
a = np.random.rand(4,3)
a

array([[0.23744884, 0.95330293, 0.90616708],
       [0.10730329, 0.09940869, 0.21995625],
       [0.67033253, 0.02880077, 0.97703987],
       [0.24664812, 0.91427597, 0.29471569]])

In [17]:
b = torch.from_numpy(a)
b

tensor([[0.2374, 0.9533, 0.9062],
        [0.1073, 0.0994, 0.2200],
        [0.6703, 0.0288, 0.9770],
        [0.2466, 0.9143, 0.2947]], dtype=torch.float64)

In [18]:
b.numpy()

array([[0.23744884, 0.95330293, 0.90616708],
       [0.10730329, 0.09940869, 0.21995625],
       [0.67033253, 0.02880077, 0.97703987],
       [0.24664812, 0.91427597, 0.29471569]])

In [19]:
# Multiply PyTorch Tensor by 2, in place
b.mul_(2)

tensor([[0.4749, 1.9066, 1.8123],
        [0.2146, 0.1988, 0.4399],
        [1.3407, 0.0576, 1.9541],
        [0.4933, 1.8286, 0.5894]], dtype=torch.float64)

In [20]:
# Numpy array matches new values from Tensor
a

array([[0.47489768, 1.90660586, 1.81233417],
       [0.21460658, 0.19881739, 0.43991249],
       [1.34066505, 0.05760154, 1.95407974],
       [0.49329624, 1.82855194, 0.58943139]])

In [ ]:

import matplotlib.pyplot as plt
from torchvision import datasets, transforms


# Define a transform to normalize the data
transform = transforms.Compose([transforms.ToTensor(),
                              transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),
                             ])
# Download and load the training data
trainset = datasets.MNIST('MNIST_data/', download=True, train=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)

# Download and load the test data
testset = datasets.MNIST('MNIST_data/', download=True, train=False, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=64, shuffle=True)

In [ ]:
dataiter = iter(trainloader)
images, labels = dataiter.next()

In [ ]:
plt.imshow(images[1].numpy().squeeze(), cmap='Greys_r')

In [ ]:
from torch import nn
from torch import optim
import torch.nn.functional as F
from torch.autograd import Variable

In [ ]:
class Network(nn.Module):
    def __init__(self):
        super().__init__()
        # Defining the layers, 128, 64, 10 units each
        self.fc1 = nn.Linear(784, 128)
        self.fc2 = nn.Linear(128, 64)
        # Output layer, 10 units - one for each digit
        self.fc3 = nn.Linear(64, 10)
        
    def forward(self, x):
        ''' Forward pass through the network, returns the output logits '''
        
        x = self.fc1(x)
        x = F.relu(x)
        x = self.fc2(x)
        x = F.relu(x)
        x = self.fc3(x)
        
        return x
    
    def predict(self, x):
        ''' This function for predicts classes by calculating the softmax '''
        logits = self.forward(x)
        return F.softmax(logits)

net = Network()
net

In [ ]:
print(net.fc1.weight)
print(net.fc1.bias)